import os
import xml.etree.ElementTree as ET

translations = {
    "ru": {
        "msg_press_device_graph": "Нажмите на устройство для просмотра графика",
        "msg_no_devices": "Нет подключенных устройств",
        "msg_devices_connected": "Подключено устройств: %1$d",
        "msg_no_ethernet": "Нет ethernet устройств",
        "format_speed_dl": "Скачивание: %.2f Мбит/с",
        "format_speed_ul": "Загрузка: %.2f Мбит/с",
        "format_bytes_kb": "%.1f КБ",
        "format_bytes_mb": "%.1f МБ",
        "format_bytes_gb": "%.1f ГБ",
        "msg_link_speed": "Скорость линка: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Внимание: трафик является общим для данного порта",
        "msg_traffic_unavailable": "Трафик недоступен",
        "msg_install_nlbwmon": "Установите nlbwmon для отслеживания трафика.",
        "format_download_speed": "Скачивание: %.2f Мбит/с",
        "format_upload_speed": "Загрузка: %.2f Мбит/с",
        "msg_no_selected_device": "Устройство не выбрано",
        "wifi_6_ghz": "Wi-Fi 6 ГГц",
        "wifi_5_ghz": "Wi-Fi 5 ГГц",
        "wifi_24_ghz": "Wi-Fi 2.4 ГГц",
        "wifi_other": "Wi-Fi Другое",
        "ethernet": "Ethernet",
        "label_today_colon": "Сегодня:",
        "port_approximate": "(примерно)",
        "port_unknown": "(неизвестно)",
        "action_close": "Закрыть"
    },
    "uk": {
        "msg_press_device_graph": "Натисніть на пристрій для перегляду графіка",
        "msg_no_devices": "Немає підключених пристроїв",
        "msg_devices_connected": "Підключено пристроїв: %1$d",
        "msg_no_ethernet": "Немає ethernet пристроїв",
        "format_speed_dl": "Завантаження: %.2f Мбіт/с",
        "format_speed_ul": "Віддача: %.2f Мбіт/с",
        "format_bytes_kb": "%.1f КБ",
        "format_bytes_mb": "%.1f МБ",
        "format_bytes_gb": "%.1f ГБ",
        "msg_link_speed": "Швидкість з'єднання: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Увага: трафік є спільним для цього порту",
        "msg_traffic_unavailable": "Трафік недоступний",
        "msg_install_nlbwmon": "Встановіть nlbwmon для відстеження трафіку.",
        "format_download_speed": "Завантаження: %.2f Мбіт/с",
        "format_upload_speed": "Віддача: %.2f Мбіт/с",
        "msg_no_selected_device": "Пристрій не вибрано",
        "wifi_6_ghz": "Wi-Fi 6 ГГц",
        "wifi_5_ghz": "Wi-Fi 5 ГГц",
        "wifi_24_ghz": "Wi-Fi 2.4 ГГц",
        "wifi_other": "Wi-Fi Інше",
        "ethernet": "Ethernet",
        "label_today_colon": "Сьогодні:",
        "port_approximate": "(приблизно)",
        "port_unknown": "(невідомо)",
        "action_close": "Закрити"
    },
    "be": {
        "msg_press_device_graph": "Націсніце на прыладу для прагляду графіка",
        "msg_no_devices": "Няма падлучаных прылад",
        "msg_devices_connected": "Падлучана прылад: %1$d",
        "msg_no_ethernet": "Няма ethernet прылад",
        "format_speed_dl": "Спампоўванне: %.2f Мбіт/с",
        "format_speed_ul": "Загрузка: %.2f Мбіт/с",
        "format_bytes_kb": "%.1f КБ",
        "format_bytes_mb": "%.1f МБ",
        "format_bytes_gb": "%.1f ГБ",
        "msg_link_speed": "Хуткасць злучэння: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Увага: трафік з'яўляецца агульным для гэтага порта",
        "msg_traffic_unavailable": "Трафік недаступны",
        "msg_install_nlbwmon": "Усталюйце nlbwmon для адсочвання трафіку.",
        "format_download_speed": "Спампоўванне: %.2f Мбіт/с",
        "format_upload_speed": "Загрузка: %.2f Мбіт/с",
        "msg_no_selected_device": "Прылада не выбрана",
        "wifi_6_ghz": "Wi-Fi 6 ГГц",
        "wifi_5_ghz": "Wi-Fi 5 ГГц",
        "wifi_24_ghz": "Wi-Fi 2.4 ГГц",
        "wifi_other": "Wi-Fi Іншае",
        "ethernet": "Ethernet",
        "label_today_colon": "Сёння:",
        "port_approximate": "(прыкладна)",
        "port_unknown": "(невядома)",
        "action_close": "Закрыць"
    },
    "de": {
        "msg_press_device_graph": "Tippen Sie auf ein Gerät, um sein Diagramm anzuzeigen",
        "msg_no_devices": "Keine verbundenen Geräte",
        "msg_devices_connected": "%1$d Geräte verbunden",
        "msg_no_ethernet": "Keine Ethernet-Geräte",
        "format_speed_dl": "Download: %.2f Mbps",
        "format_speed_ul": "Upload: %.2f Mbps",
        "format_bytes_kb": "%.1f KB",
        "format_bytes_mb": "%.1f MB",
        "format_bytes_gb": "%.1f GB",
        "msg_link_speed": "Verbindungsgeschwindigkeit: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Warnung: Der Datenverkehr wird für diesen Port geteilt",
        "msg_traffic_unavailable": "Datenverkehr nicht verfügbar",
        "msg_install_nlbwmon": "Installieren Sie nlbwmon, um den Datenverkehr zu verfolgen.",
        "format_download_speed": "Download: %.2f Mbps",
        "format_upload_speed": "Upload: %.2f Mbps",
        "msg_no_selected_device": "Kein Gerät ausgewählt",
        "wifi_6_ghz": "Wi-Fi 6 GHz",
        "wifi_5_ghz": "Wi-Fi 5 GHz",
        "wifi_24_ghz": "Wi-Fi 2.4 GHz",
        "wifi_other": "Wi-Fi Andere",
        "ethernet": "Ethernet",
        "label_today_colon": "Heute:",
        "port_approximate": "(ungefähr)",
        "port_unknown": "(unbekannt)",
        "action_close": "Schließen"
    },
    "es": {
        "msg_press_device_graph": "Toca un dispositivo para ver su gráfico",
        "msg_no_devices": "No hay dispositivos conectados",
        "msg_devices_connected": "%1$d dispositivos conectados",
        "msg_no_ethernet": "No hay dispositivos ethernet",
        "format_speed_dl": "Descarga: %.2f Mbps",
        "format_speed_ul": "Subida: %.2f Mbps",
        "format_bytes_kb": "%.1f KB",
        "format_bytes_mb": "%.1f MB",
        "format_bytes_gb": "%.1f GB",
        "msg_link_speed": "Velocidad de enlace: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Advertencia: el tráfico es compartido para este puerto",
        "msg_traffic_unavailable": "Tráfico no disponible",
        "msg_install_nlbwmon": "Instale nlbwmon para rastrear el tráfico.",
        "format_download_speed": "Descarga: %.2f Mbps",
        "format_upload_speed": "Subida: %.2f Mbps",
        "msg_no_selected_device": "Ningún dispositivo seleccionado",
        "wifi_6_ghz": "Wi-Fi 6 GHz",
        "wifi_5_ghz": "Wi-Fi 5 GHz",
        "wifi_24_ghz": "Wi-Fi 2.4 GHz",
        "wifi_other": "Wi-Fi Otros",
        "ethernet": "Ethernet",
        "label_today_colon": "Hoy:",
        "port_approximate": "(aproximado)",
        "port_unknown": "(desconocido)",
        "action_close": "Cerrar"
    },
    "fr": {
        "msg_press_device_graph": "Appuyez sur un appareil pour voir son graphique",
        "msg_no_devices": "Aucun appareil connecté",
        "msg_devices_connected": "%1$d appareils connectés",
        "msg_no_ethernet": "Aucun appareil ethernet",
        "format_speed_dl": "Téléchargement : %.2f Mbps",
        "format_speed_ul": "Envoi : %.2f Mbps",
        "format_bytes_kb": "%.1f Ko",
        "format_bytes_mb": "%.1f Mo",
        "format_bytes_gb": "%.1f Go",
        "msg_link_speed": "Vitesse de liaison : %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Attention : le trafic est partagé pour ce port",
        "msg_traffic_unavailable": "Trafic indisponible",
        "msg_install_nlbwmon": "Installez nlbwmon pour suivre le trafic.",
        "format_download_speed": "Téléchargement : %.2f Mbps",
        "format_upload_speed": "Envoi : %.2f Mbps",
        "msg_no_selected_device": "Aucun appareil sélectionné",
        "wifi_6_ghz": "Wi-Fi 6 GHz",
        "wifi_5_ghz": "Wi-Fi 5 GHz",
        "wifi_24_ghz": "Wi-Fi 2.4 GHz",
        "wifi_other": "Wi-Fi Autre",
        "ethernet": "Ethernet",
        "label_today_colon": "Aujourd'hui :",
        "port_approximate": "(approximatif)",
        "port_unknown": "(inconnu)",
        "action_close": "Fermer"
    },
    "it": {
        "msg_press_device_graph": "Tocca un dispositivo per vedere il grafico",
        "msg_no_devices": "Nessun dispositivo connesso",
        "msg_devices_connected": "%1$d dispositivi connessi",
        "msg_no_ethernet": "Nessun dispositivo ethernet",
        "format_speed_dl": "Download: %.2f Mbps",
        "format_speed_ul": "Upload: %.2f Mbps",
        "format_bytes_kb": "%.1f KB",
        "format_bytes_mb": "%.1f MB",
        "format_bytes_gb": "%.1f GB",
        "msg_link_speed": "Velocità del link: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Avviso: il traffico è condiviso per questa porta",
        "msg_traffic_unavailable": "Traffico non disponibile",
        "msg_install_nlbwmon": "Installa nlbwmon per monitorare il traffico.",
        "format_download_speed": "Download: %.2f Mbps",
        "format_upload_speed": "Upload: %.2f Mbps",
        "msg_no_selected_device": "Nessun dispositivo selezionato",
        "wifi_6_ghz": "Wi-Fi 6 GHz",
        "wifi_5_ghz": "Wi-Fi 5 GHz",
        "wifi_24_ghz": "Wi-Fi 2.4 GHz",
        "wifi_other": "Wi-Fi Altro",
        "ethernet": "Ethernet",
        "label_today_colon": "Oggi:",
        "port_approximate": "(approssimativo)",
        "port_unknown": "(sconosciuto)",
        "action_close": "Chiudi"
    },
    "pt": {
        "msg_press_device_graph": "Toque em um dispositivo para ver seu gráfico",
        "msg_no_devices": "Nenhum dispositivo conectado",
        "msg_devices_connected": "%1$d dispositivos conectados",
        "msg_no_ethernet": "Nenhum dispositivo ethernet",
        "format_speed_dl": "Download: %.2f Mbps",
        "format_speed_ul": "Upload: %.2f Mbps",
        "format_bytes_kb": "%.1f KB",
        "format_bytes_mb": "%.1f MB",
        "format_bytes_gb": "%.1f GB",
        "msg_link_speed": "Velocidade do link: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Aviso: o tráfego é compartilhado para esta porta",
        "msg_traffic_unavailable": "Tráfego indisponível",
        "msg_install_nlbwmon": "Instale nlbwmon para monitorar o tráfego.",
        "format_download_speed": "Download: %.2f Mbps",
        "format_upload_speed": "Upload: %.2f Mbps",
        "msg_no_selected_device": "Nenhum dispositivo selecionado",
        "wifi_6_ghz": "Wi-Fi 6 GHz",
        "wifi_5_ghz": "Wi-Fi 5 GHz",
        "wifi_24_ghz": "Wi-Fi 2.4 GHz",
        "wifi_other": "Wi-Fi Outro",
        "ethernet": "Ethernet",
        "label_today_colon": "Hoje:",
        "port_approximate": "(aproximado)",
        "port_unknown": "(desconhecido)",
        "action_close": "Fechar"
    },
    "da": {
        "msg_press_device_graph": "Tryk på en enhed for at se dens graf",
        "msg_no_devices": "Ingen tilsluttede enheder",
        "msg_devices_connected": "%1$d enheder tilsluttet",
        "msg_no_ethernet": "Ingen ethernet-enheder",
        "format_speed_dl": "Download: %.2f Mbps",
        "format_speed_ul": "Upload: %.2f Mbps",
        "format_bytes_kb": "%.1f KB",
        "format_bytes_mb": "%.1f MB",
        "format_bytes_gb": "%.1f GB",
        "msg_link_speed": "Linkhastighed: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Advarsel: Trafikken deles for denne port",
        "msg_traffic_unavailable": "Trafik ikke tilgængelig",
        "msg_install_nlbwmon": "Installer nlbwmon for at spore trafikken.",
        "format_download_speed": "Download: %.2f Mbps",
        "format_upload_speed": "Upload: %.2f Mbps",
        "msg_no_selected_device": "Ingen enhed valgt",
        "wifi_6_ghz": "Wi-Fi 6 GHz",
        "wifi_5_ghz": "Wi-Fi 5 GHz",
        "wifi_24_ghz": "Wi-Fi 2.4 GHz",
        "wifi_other": "Wi-Fi Andet",
        "ethernet": "Ethernet",
        "label_today_colon": "I dag:",
        "port_approximate": "(omtrentlig)",
        "port_unknown": "(ukendt)",
        "action_close": "Luk"
    },
    "fi": {
        "msg_press_device_graph": "Napauta laitetta nähdäksesi sen kaavion",
        "msg_no_devices": "Ei yhdistettyjä laitteita",
        "msg_devices_connected": "%1$d laitetta yhdistetty",
        "msg_no_ethernet": "Ei ethernet-laitteita",
        "format_speed_dl": "Lataus: %.2f Mbps",
        "format_speed_ul": "Lähetys: %.2f Mbps",
        "format_bytes_kb": "%.1f kt",
        "format_bytes_mb": "%.1f Mt",
        "format_bytes_gb": "%.1f Gt",
        "msg_link_speed": "Linkin nopeus: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Varoitus: liikenne on jaettu tälle portille",
        "msg_traffic_unavailable": "Liikenne ei ole saatavilla",
        "msg_install_nlbwmon": "Asenna nlbwmon liikenteen seuraamiseksi.",
        "format_download_speed": "Lataus: %.2f Mbps",
        "format_upload_speed": "Lähetys: %.2f Mbps",
        "msg_no_selected_device": "Laitetta ei ole valittu",
        "wifi_6_ghz": "Wi-Fi 6 GHz",
        "wifi_5_ghz": "Wi-Fi 5 GHz",
        "wifi_24_ghz": "Wi-Fi 2.4 GHz",
        "wifi_other": "Wi-Fi Muu",
        "ethernet": "Ethernet",
        "label_today_colon": "Tänään:",
        "port_approximate": "(arvio)",
        "port_unknown": "(tuntematon)",
        "action_close": "Sulje"
    },
    "kk": {
        "msg_press_device_graph": "Графикті көру үшін құрылғыны түртіңіз",
        "msg_no_devices": "Қосылған құрылғылар жоқ",
        "msg_devices_connected": "%1$d құрылғы қосылған",
        "msg_no_ethernet": "Ethernet құрылғылары жоқ",
        "format_speed_dl": "Жүктеп алу: %.2f Мбит/с",
        "format_speed_ul": "Жүктеп салу: %.2f Мбит/с",
        "format_bytes_kb": "%.1f КБ",
        "format_bytes_mb": "%.1f МБ",
        "format_bytes_gb": "%.1f ГБ",
        "msg_link_speed": "Байланыс жылдамдығы: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Ескерту: трафик осы порт үшін ортақ",
        "msg_traffic_unavailable": "Трафик қолжетімсіз",
        "msg_install_nlbwmon": "Трафикті бақылау үшін nlbwmon орнатыңыз.",
        "format_download_speed": "Жүктеп алу: %.2f Мбит/с",
        "format_upload_speed": "Жүктеп салу: %.2f Мбит/с",
        "msg_no_selected_device": "Құрылғы таңдалмады",
        "wifi_6_ghz": "Wi-Fi 6 ГГц",
        "wifi_5_ghz": "Wi-Fi 5 ГГц",
        "wifi_24_ghz": "Wi-Fi 2.4 ГГц",
        "wifi_other": "Wi-Fi Басқа",
        "ethernet": "Ethernet",
        "label_today_colon": "Бүгін:",
        "port_approximate": "(шамамен)",
        "port_unknown": "(белгісіз)",
        "action_close": "Жабу"
    },
    "lt": {
        "msg_press_device_graph": "Palieskite įrenginį, kad pamatytumėte jo grafiką",
        "msg_no_devices": "Nėra prijungtų įrenginių",
        "msg_devices_connected": "Prijungta įrenginių: %1$d",
        "msg_no_ethernet": "Nėra ethernet įrenginių",
        "format_speed_dl": "Atsisiuntimas: %.2f Mbps",
        "format_speed_ul": "Išsiuntimas: %.2f Mbps",
        "format_bytes_kb": "%.1f KB",
        "format_bytes_mb": "%.1f MB",
        "format_bytes_gb": "%.1f GB",
        "msg_link_speed": "Ryšio greitis: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Įspėjimas: srautas yra bendras šiam prievadui",
        "msg_traffic_unavailable": "Srautas nepasiekiamas",
        "msg_install_nlbwmon": "Įdiekite nlbwmon srautui stebėti.",
        "format_download_speed": "Atsisiuntimas: %.2f Mbps",
        "format_upload_speed": "Išsiuntimas: %.2f Mbps",
        "msg_no_selected_device": "Įrenginys nepasirinktas",
        "wifi_6_ghz": "Wi-Fi 6 GHz",
        "wifi_5_ghz": "Wi-Fi 5 GHz",
        "wifi_24_ghz": "Wi-Fi 2.4 GHz",
        "wifi_other": "Wi-Fi Kita",
        "ethernet": "Ethernet",
        "label_today_colon": "Šiandien:",
        "port_approximate": "(apytiksliai)",
        "port_unknown": "(nežinoma)",
        "action_close": "Uždaryti"
    },
    "lv": {
        "msg_press_device_graph": "Pieskarieties ierīcei, lai skatītu tās grafiku",
        "msg_no_devices": "Nav pievienotu ierīču",
        "msg_devices_connected": "Pievienotas ierīces: %1$d",
        "msg_no_ethernet": "Nav ethernet ierīču",
        "format_speed_dl": "Lejupielāde: %.2f Mbps",
        "format_speed_ul": "Augšupielāde: %.2f Mbps",
        "format_bytes_kb": "%.1f KB",
        "format_bytes_mb": "%.1f MB",
        "format_bytes_gb": "%.1f GB",
        "msg_link_speed": "Saites ātrums: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Brīdinājums: trafiks ir koplietots šim portam",
        "msg_traffic_unavailable": "Trafiks nav pieejams",
        "msg_install_nlbwmon": "Instalējiet nlbwmon, lai izsekotu trafiku.",
        "format_download_speed": "Lejupielāde: %.2f Mbps",
        "format_upload_speed": "Augšupielāde: %.2f Mbps",
        "msg_no_selected_device": "Ierīce nav izvēlēta",
        "wifi_6_ghz": "Wi-Fi 6 GHz",
        "wifi_5_ghz": "Wi-Fi 5 GHz",
        "wifi_24_ghz": "Wi-Fi 2.4 GHz",
        "wifi_other": "Wi-Fi Cits",
        "ethernet": "Ethernet",
        "label_today_colon": "Šodien:",
        "port_approximate": "(aptuveni)",
        "port_unknown": "(nezināms)",
        "action_close": "Aizvērt"
    },
    "sv": {
        "msg_press_device_graph": "Tryck på en enhet för att se dess diagram",
        "msg_no_devices": "Inga anslutna enheter",
        "msg_devices_connected": "%1$d anslutna enheter",
        "msg_no_ethernet": "Inga ethernet-enheter",
        "format_speed_dl": "Nedladdning: %.2f Mbps",
        "format_speed_ul": "Uppladdning: %.2f Mbps",
        "format_bytes_kb": "%.1f KB",
        "format_bytes_mb": "%.1f MB",
        "format_bytes_gb": "%.1f GB",
        "msg_link_speed": "Länkhastighet: %1$s Rx / %2$s Tx",
        "msg_shared_traffic_warning": "Varning: trafiken delas för den här porten",
        "msg_traffic_unavailable": "Trafik ej tillgänglig",
        "msg_install_nlbwmon": "Installera nlbwmon för att spåra trafik.",
        "format_download_speed": "Nedladdning: %.2f Mbps",
        "format_upload_speed": "Uppladdning: %.2f Mbps",
        "msg_no_selected_device": "Ingen enhet vald",
        "wifi_6_ghz": "Wi-Fi 6 GHz",
        "wifi_5_ghz": "Wi-Fi 5 GHz",
        "wifi_24_ghz": "Wi-Fi 2.4 GHz",
        "wifi_other": "Wi-Fi Annat",
        "ethernet": "Ethernet",
        "label_today_colon": "Idag:",
        "port_approximate": "(ungefärlig)",
        "port_unknown": "(okänd)",
        "action_close": "Stäng"
    }
}

for lang, data in translations.items():
    file_path = f"app/src/main/res/values-{lang}/strings.xml"
    if os.path.exists(file_path):
        tree = ET.parse(file_path)
        root = tree.getroot()
        for key, value in data.items():
            elem = root.find(f".//string[@name='{key}']")
            if elem is not None:
                elem.text = value
            else:
                new_elem = ET.SubElement(root, "string")
                new_elem.set("name", key)
                new_elem.text = value
        tree.write(file_path, encoding='utf-8', xml_declaration=True)
